spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/pagination_ex
    username: root
    password: cockpybara # 비밀번호는 환경 변수 등을 통해 관리하는 것이 좋습니다.
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update # 또는 validate
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
